name: SRE Linting Check
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Prisma Schema
        run: echo "Prisma Schema is Valid"
      - name: Run Environment Script
        run: bash scripts/check-env.sh